# Generated by Django 4.1.5 on 2023-01-20 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currentincexp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_cash_flow', models.IntegerField()),
                ('year', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('currentincexp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currentincexp.currentincexp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
