# Generated by Django 4.1.5 on 2023-01-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default='2023-01-23'),
            preserve_default=False,
        ),
    ]
